Update vndklite.yml

diff --git a/.github/workflows/vndklite.yml b/.github/workflows/vndklite.yml
--- a/.github/workflows/vndklite.yml
+++ b/.github/workflows/vndklite.yml
@@ -41,11 +41,13 @@ jobs:
           sudo make altinstall
           sudo ln -s /usr/local/bin/python2.7 /usr/local/bin/python2
 
-      - name: Download system.img
-        run: |
-          wget "$IMAGE_URL" -O system.img
-          file system.img | grep -q "ext[2-4]\|f2fs" || { echo "Invalid system.img"; exit 1; }
-
+    - name: Download and extract system.img.xz
+  run: |
+    wget "$IMAGE_URL" -O system.img.xz
+    unxz system.img.xz
+    mv system.img system.img.raw
+    file system.img.raw | grep -q "ext[2-4]\|f2fs" || { echo "Invalid system.img"; exit 1; }
+      
       - name: Convert to VNDKLITE
         run: |
           if [ ! -f vndklite/lite-adapter.sh ]; then
